```{r}
#importa dados, string vazio como NA, string como fatores
url <- "https://raw.githubusercontent.com/anaiza-z/curso-ciencia-de-dados/main/Dados/Churn.csv"
dados = read.csv(url, sep = ";", na.strings = "", stringsAsFactors = T)
head(dados) 
summary(dados)
```
```{r}
#dar nomes corretos para as colunas
colnames(dados) = c("ID", "Score", "Estado", "Genero", "Idade", "Patrimonio", "Saldo", "Produtos", "TemCartCredito", "Ativo", "Salario", "Saiu")
head(dados)
```
```{r}
#explorar dados categóricos
counts = table(dados$Estado)
barplot(counts, main="Estados", xlab="Estados")
counts1 = table(dados$Genero)
barplot(counts1, main="Gêneros", xlab="Gêneros")
```

explorar colunas numéricas
```{r}
summary(dados$Score)
boxplot(dados$Score)
hist(dados$Score, xlab = "Score", main = "Histograma do Score", ylab = "Frequência")
```
```{r}
summary(dados$Idade)
boxplot(dados$Idade)
hist(dados$Idade, xlab = "Idade", main = "Histograma da idade", ylab = "Frequência")
```
```{r}
summary(dados$Saldo)
boxplot(dados$Saldo)
hist(dados$Saldo, xlab = "Saldo", main = "Histograma do Saldo", ylab = "Frequência")
```
```{r}
summary(dados$Salario)
boxplot(dados$Salario)
hist(dados$Salario, xlab = "Salario", main = "Histograma do Salario", ylab = "Frequência")
```

valores faltantes - NAs
```{r}
dados[!complete.cases(dados),]
```
correção de salário
```{r}
#resumo da coluna
summary(dados$Salario)
#ver mediana
median(dados$Salario, na.rm = T )
#substituir NA por mediana
dados[is.na(dados$Salario),]$Salario = median(dados$Salario, na.rm = T )
#verificar se ainda tem NA
dados[!complete.cases(dados$Salario),]
```
falta de pradronização em gênero
```{r}
#ver valores
unique(dados$Genero) #os valores que estao nessa coluna
summary(dados$Genero) #resumo da coluna
#transformar NA e M em masculino
dados[is.na(dados$Genero) | dados$Genero == "M", ]$Genero = "Masculino"
#transformar F e Fem em feminino
dados[dados$Genero == "F" | dados$Genero == "Fem", ]$Genero = "Feminino"
summary(dados$Genero)
#remover levels nao utilizados
dados$Genero = factor(dados$Genero)
summary(dados$Genero)
```
idades fora do dominio
```{r}
summary(dados$Idade)
#visualizar idades anormais
dados[dados$Idade < 0 | dados$Idade > 110,]$Idade
#ver mediana
median(dados$Idade)
#substituição
dados[dados$Idade < 0 | dados$Idade > 110,]$Idade = median(dados$Idade)
#verificar se ainda tem idade anormal
dados[dados$Idade < 0 | dados$Idade > 110,]
summary(dados$Idade)
```
dados duplicados
```{r}
#buscar duplicados pelo ID
x = dados[duplicated(dados$ID),]
x
#excluir pelo indice da linha
dados = dados[-c(82),]
#verificando duplicados
x = dados[duplicated(dados$ID),]
x
```
estado fora do dominio
```{r}
unique(dados$Estado)
summary(dados$Estado)
#preencher com a moda, RS
dados[!dados$Estado %in% c("RS", "SC", "PR"),]$Estado = "RS"
summary(dados$Estado)
#revomendo fatores inuteis
dados$Estado = factor(dados$Estado)
summary(dados$Estado)
```
outliers
```{r}
#criando um parametro com desvio padrão
desv = sd(dados$Salario)
desv
dados[dados$Salario >= 2*desv,]$Salario
#visualizar os desvios em boxplot
boxplot(dados$Salario)
boxplot(dados$Salario, outline = F) #sem outliers
#visualizar quais sao os desvios atraves do boxplot
x = boxplot(dados$Salario)$out
x
#substituir por mediana
median(dados$Salario)
dados[dados$Salario >= 2*desv,]$Salario = median(dados$Salario)
#verificar se ainda tem outlier
dados[dados$Salario >= 2*desv,]$Salario
```





















